language: node_js

services:
    - postgresql

node_js:
    - "12"

before_script:
    - psql -c 'create database spms;' -U postgres
    - yarn
    - yarn global add codecov

script:
    - yarn test
    - codecov
