trigger:
- main

pr:
- main

variables:
  isPullRequest: ${{eq(variables['Build.Reason'], 'PullRequest')}}
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: ubuntu-22.04

parameters:
  - name: awsCredentials
    displayName: AWS Credentials
    type: string
    default: 'AWS-Dev-AssumeRole'
  - name: region
    displayName: AWS Region
    type: string
    default: 'ap-southeast-1'

steps:
- template: build.yml
  parameters:
    awsCredentials: ${{ parameters.awsCredentials }}
    region: ${{ parameters.region }}
- ${{ if and(succeeded(), eq(variables.isPullRequest, 'false'), eq(variables.isMain, 'true')) }}:
  - template: deploy.yml
    condition: 
    parameters:
      awsCredentials: ${{ parameters.awsCredentials }}
      region: ${{ parameters.region }}
