version: '3'
services:
  backend:
    build:
      context: packages/api
      args:
        - NODE_AUTH_TOKEN
    image: spms-api:latest
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: "production"
      PORT: 5000
      DATABASE_URL: "postgres://postgres:devpassword@db:5432/spms"
      HOST: "localhost"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: spms
  frontend:
    build:
      context: packages/frontend
    image: spms:latest
    ports:
      - "8000:80"
    environment:
      NODE_ENV: "production"
      VUE_APP_API_URL: "http://localhost:5000"
