name: Build Front End
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/frontend/**'
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn bootstrap
      - name: Build
        run: yarn lerna run build --scope @bervproject/spms-ui
        env:
          NODE_ENV: production
          PUBLIC_URL: /SimplePasswordManagerService/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/frontend/dist


