# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
    push:
        branches: [master]
        tags:
          - v*
    pull_request:
        branches: [master]
env:
  IMAGE_NAME_API: spms
  IMAGE_NAME_UI: spms-ui
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HEROKU_APP_NAME: spms-berv
  CI: true
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      # Label used to access the service container
      postgres:
        ports:
          - 5432:5432
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: spms
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - name: Build & Test
        run: |
          yarn
          yarn bootstrap
          yarn lint
          yarn test
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/spms
      - name: Build
        run: |
          yarn build
        env:
          NODE_ENV: production
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
  docker-build:
    # Ensure test job passes before pushing image.
    needs: build
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Build & Test
        run: |
          docker-compose build
          docker-compose up -d
          # call API
          curl http://localhost:5000 --retry-connrefused --retry-delay 5 --retry-max-time 60
          # call UI
          curl http://localhost:8000 --retry-connrefused --retry-delay 5 --retry-max-time 60
          docker-compose down
  docker-push:
    # Ensure test job passes before pushing image.
    needs: docker-build
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build . --file api.Dockerfile --tag $IMAGE_NAME_API --build-arg NODE_AUTH_TOKEN=${NODE_AUTH_TOKEN}
          docker build . --file frontend.Dockerfile --tag $IMAGE_NAME_UI
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID_API=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME_API
          IMAGE_ID_UI=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME_UI
          # Change all uppercase to lowercase
          IMAGE_ID_API=$(echo $IMAGE_ID_API | tr '[A-Z]' '[a-z]')
          IMAGE_ID_UI=$(echo $IMAGE_ID_UI | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID_API=$IMAGE_ID_API
          echo IMAGE_ID_UI=$IMAGE_ID_UI
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME_API $IMAGE_ID_API:$VERSION
          docker tag $IMAGE_NAME_UI $IMAGE_ID_UI:$VERSION
          docker push $IMAGE_ID_API:$VERSION
          docker push $IMAGE_ID_UI:$VERSION
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "" #Must be unique in Heroku
          heroku_email: "bervianto.leo@gmail.com"
          justlogin: true
      - name: Heroku Container Login, Update & Push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          heroku update
          heroku container:login
          HEROKU_IMAGE=registry.heroku.com/$HEROKU_APP_NAME/web
          docker tag $IMAGE_NAME_API $HEROKU_IMAGE
          docker push $HEROKU_IMAGE
          heroku container:release web --app=${HEROKU_APP_NAME}
      - name: Install doctl
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Push to DO
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          doctl registry login
          DO_IMAGE=registry.digitalocean.com/$IMAGE_NAME_UI
          docker tag $IMAGE_NAME_UI $DO_IMAGE
          docker push $DO_IMAGE
          heroku container:release web --app=${HEROKU_APP_NAME}
